import { APIGatewayProxyEvent, APIGatewayProxyResult, Context } from 'aws-lambda'
import { create } from '../helpers/dynamo-helpers/create'
import { getAuthenticatedRecipient } from '../middleware/auth-middleware'

interface SubscribeRequest {
  subscription_id: string
  endpoint: string
  keys: {
    p256dh: string
    auth: string
  }
  user_agent?: string
}

/**
 * Subscribe to Push Notifications
 *
 * Registers a new push notification subscription for the authenticated user.
 * Supports multiple devices per user (one subscription per device).
 *
 * Route: POST /api/push/subscribe (protected)
 *
 * Request Body:
 * {
 *   subscription_id: string,  // UUID generated by client
 *   endpoint: string,          // Push service endpoint URL
 *   keys: {
 *     p256dh: string,          // Client public key (base64)
 *     auth: string             // Client auth secret (base64)
 *   },
 *   user_agent?: string        // Optional browser/device info
 * }
 */
export const handler = async (
  event: APIGatewayProxyEvent,
  _context: Context
): Promise<APIGatewayProxyResult> => {
  try {
    // Authenticate and get phone number
    const authResult = await getAuthenticatedRecipient(event)
    if (!authResult.success) {
      return {
        statusCode: authResult.statusCode,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: authResult.error }),
      }
    }

    const phoneNumber = authResult.phoneNumber

    // Get table name from environment
    const tableName = process.env.PUSH_SUBSCRIPTIONS_TABLE
    if (!tableName) {
      throw new Error('PUSH_SUBSCRIPTIONS_TABLE environment variable is not set')
    }

    // Parse request body
    if (!event.body) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Request body is required' }),
      }
    }

    const request = JSON.parse(event.body) as SubscribeRequest

    // Validate required fields
    if (!request.subscription_id || !request.endpoint || !request.keys) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          error: 'Missing required fields: subscription_id, endpoint, keys',
        }),
      }
    }

    // Validate endpoint format (must be HTTPS)
    if (!request.endpoint.startsWith('https://')) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Endpoint must be an HTTPS URL' }),
      }
    }

    // Validate keys are present
    if (!request.keys.p256dh || !request.keys.auth) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'Keys must include p256dh and auth' }),
      }
    }

    // Validate subscription_id is UUID format
    const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
    if (!uuidRegex.test(request.subscription_id)) {
      return {
        statusCode: 400,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ error: 'subscription_id must be a valid UUID' }),
      }
    }

    // Create subscription record in DynamoDB
    const now = new Date().toISOString()
    await create({
      tableName,
      key: {
        phone_number: phoneNumber,
        subscription_id: request.subscription_id,
      },
      record: {
        endpoint: request.endpoint,
        keys: request.keys,
        user_agent: request.user_agent || '',
        created_at: now,
        last_used: now,
        status: 'active',
      },
    })

    console.log(`Push subscription created: ${phoneNumber} / ${request.subscription_id}`)

    return {
      statusCode: 200,
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        message: 'Push subscription created successfully',
        subscription_id: request.subscription_id,
      }),
    }
  } catch (error) {
    console.error('Error subscribing to push notifications:', error)
    return {
      statusCode: 500,
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        error: 'Failed to subscribe to push notifications',
        message: error instanceof Error ? error.message : 'Unknown error',
      }),
    }
  }
}
